[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn run:app --bind 0.0.0.0:$PORT --workers 3 --timeout 300"
healthcheckPath = "/login"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
